# Defaults match this machine (CUDA 11.8 + ORT CUDA11). On a new host override:
#   make staf CUDA_HOME=... ORT_ROOT=... CUDNN_LIB=...
# or: source $(STAF_ROOT)/scripts/staf_gpu_env.sh  then export the Make vars.
# Discovery helper: scripts/staf_gpu_env.sh

SHELL = /bin/sh

STAF_ROOT ?= /home/francegm/AlphaNesGpu
LIBSTAF_DIR ?= $(STAF_ROOT)/libstaf/build
JMD_SRC ?= /home/francegm/neuralmdGPU/full_atom/src
CUDA_HOME ?= /home/francegm/programmi/cuda
ORT_ROOT ?= $(STAF_ROOT)/third_party/onnxruntime-cuda11
CUDNN_LIB ?= /home/francegm/programmi/cudaNN/cuda-11.8/lib

CC =		mpic++
CCFLAGS =	-g -O3 -std=c++14 -fopenmp \
		-I$(STAF_ROOT)/libstaf/include \
		-I$(STAF_ROOT)/libstaf/vendor/jmd \
		-I$(JMD_SRC) \
		-DSTAF_WITH_JMD=1
SHFLAGS =	-fPIC
DEPFLAGS =	-M

LINK =		mpic++
LINKFLAGS =	-g -O3 -fopenmp
LIB = \
		-L$(LIBSTAF_DIR) -L$(CUDA_HOME)/lib64 -L$(ORT_ROOT)/lib -L$(CUDNN_LIB) \
		-Wl,-rpath,$(CUDA_HOME)/lib64 \
		-Wl,-rpath,$(ORT_ROOT)/lib \
		-Wl,-rpath,$(CUDNN_LIB) \
		-Wl,--start-group \
		$(LIBSTAF_DIR)/libstaf.a \
		$(LIBSTAF_DIR)/libstaf_jmd_nn.a \
		$(JMD_SRC)/celle_gpu.o \
		$(JMD_SRC)/nn_io.o \
		$(JMD_SRC)/nn_smart_allocator.o \
		$(JMD_SRC)/nn_smart_allocator_gpu.o \
		$(JMD_SRC)/secure_search.o \
		$(JMD_SRC)/io.o \
		$(JMD_SRC)/log.o \
		$(JMD_SRC)/vector.o \
		$(JMD_SRC)/interaction_map.o \
		$(JMD_SRC)/src_nn/descriptor_builder/reforce.o \
		$(JMD_SRC)/src_nn/fingerprint/rad/reforce.o \
		$(JMD_SRC)/src_nn/fingerprint/ang/reforce.o \
		$(JMD_SRC)/src_nn/force/rad/reforce.o \
		$(JMD_SRC)/src_nn/force/ang/reforce.o \
		-Wl,--end-group \
		-lonnxruntime \
		-lcudart -lcuda -lgsl -lgslcblas -lpthread -ldl -lm
SIZE =		size

ARCHIVE =	ar
ARFLAGS =	-rc
SHLIBFLAGS =	-shared

LMP_INC =	-DLAMMPS_GZIP -DLAMMPS_MEMALIGN=64
MPI_INC =       -DMPICH_SKIP_MPICXX -DOMPI_SKIP_MPICXX=1
MPI_PATH =
MPI_LIB =
FFT_INC =
FFT_PATH =
FFT_LIB =
JPG_INC =
JPG_PATH =
JPG_LIB =

include Makefile.package.settings
include Makefile.package

EXTRA_INC = $(LMP_INC) $(PKG_INC) $(MPI_INC) $(FFT_INC) $(JPG_INC) $(PKG_SYSINC)
EXTRA_PATH = $(PKG_PATH) $(MPI_PATH) $(FFT_PATH) $(JPG_PATH) $(PKG_SYSPATH)
EXTRA_LIB = $(PKG_LIB) $(MPI_LIB) $(FFT_LIB) $(JPG_LIB) $(PKG_SYSLIB)
EXTRA_CPP_DEPENDS = $(PKG_CPP_DEPENDS)
EXTRA_LINK_DEPENDS = $(PKG_LINK_DEPENDS)

vpath %.cpp ..
vpath %.h ..

$(EXE): main.o $(LMPLIB) $(EXTRA_LINK_DEPENDS)
	$(LINK) $(LINKFLAGS) main.o $(EXTRA_PATH) $(LMPLINK) $(EXTRA_LIB) $(LIB) -o $@
	$(SIZE) $@

lib: $(LMPLIB)

$(LMPLIB): $(OBJ)
	$(ARCHIVE) $(ARFLAGS) $(LMPLIB) $(OBJ)

%.o:%.cpp
	$(CC) $(EXTRA_INC) $(CCFLAGS) -c $<

%.d:%.cpp
	$(CC) $(EXTRA_INC) $(DEPFLAGS) $< > $@

.PHONY: clean
clean:
	rm -f *.o *.d

sinclude *.d
