/* Smoke: load mlp_type*.bin and compare E / dE/daf vs values from a dump file
 * generated by tools/mlp_parity_ref.py, or just run self-consistency.
 */
#include "staf_mlp.h"

#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <vector>
#include <random>

int main(int argc, char** argv) {
  const char* model =
      argc > 1 ? argv[1]
               : "test/test-lammps-smoke/model_onnx_float";
  StafOptions opt;
  staf_options_default(&opt);
  opt.precision = 0;
  opt.mlp_backend = STAF_MLP_ORT;

  StafMlp* mlp = staf_mlp_create(opt.mlp_backend, model, opt.precision, 0);
  if (!mlp) {
    fprintf(stderr, "staf_mlp_smoke: create failed\n");
    return 1;
  }
  int nt = staf_mlp_ntypes(mlp);
  printf("loaded %d type nets from %s\n", nt, model);

  std::mt19937 rng(42);
  std::uniform_real_distribution<float> dist(0.01f, 2.f);

  std::vector<int> n_atoms(nt), n_af(nt);
  size_t total = 0;
  for (int t = 0; t < nt; ++t) {
    n_atoms[t] = 16;
    n_af[t] = staf_mlp_n_af(mlp, t);
    total += (size_t)n_atoms[t] * n_af[t];
  }
  std::vector<float> af(total), grad(total);
  for (size_t i = 0; i < total; ++i) af[i] = dist(rng);
  float energy = 0.f;

  StafMlpEval io{};
  io.n_type = nt;
  io.n_atoms = n_atoms.data();
  io.n_af = n_af.data();
  io.af_f32 = af.data();
  io.energy_f32 = &energy;
  io.dE_daf_f32 = grad.data();

  int rc = staf_mlp_eval(mlp, &io);
  printf("staf_mlp_eval rc=%d energy=%.8g |grad|_max=%.6g\n", rc, energy,
         [&] {
           float m = 0;
           for (float g : grad) m = std::fmax(m, std::fabs(g));
           return m;
         }());

  /* finite-difference check on one component */
  const int t0 = 0;
  const int idx = 3 * n_af[t0] + 5;
  const float eps = 1e-3f;
  float e_p = 0, e_m = 0;
  float old = af[idx];
  af[idx] = old + eps;
  staf_mlp_eval(mlp, &io);
  e_p = energy;
  af[idx] = old - eps;
  staf_mlp_eval(mlp, &io);
  e_m = energy;
  af[idx] = old;
  staf_mlp_eval(mlp, &io);
  float fd = (e_p - e_m) / (2 * eps);
  /* Note: energy is 0.5*sum(atomic); analytical grad is d(sum atomic)/daf.
   * So d(energy)/daf = 0.5 * dE_daf. */
  float ana = 0.5f * grad[idx];
  printf("FD dE/daf[%d]=%.6g  0.5*ana=%.6g  rel=%.3g\n", idx, fd, ana,
         std::fabs(fd - ana) / (std::fabs(fd) + 1e-12f));

  staf_mlp_destroy(mlp);
  if (rc != 0) return 2;
  if (std::fabs(fd - ana) / (std::fabs(fd) + 1e-12f) > 1e-2f) {
    fprintf(stderr, "staf_mlp_smoke: FD vs analytical mismatch\n");
    return 3;
  }
  printf("staf_mlp_smoke: OK\n");
  return 0;
}
