#yaml input file

#Dataset Path
dataset_folder: dataset

buffer_stream_dim_ts: 21
buffer_stream_dim_tr: 21
subsampling: 'no'

model_name: 'model_log'
restart:  only afs #model1 net_model

#Descriptor parameter
Rc: 1.9
Radial_Buffer: 30
Rc_Angular: 1.8
Angular_Buffer: 153
#Net parmater
dimension_encoder_2body: 0 5 1 3
dimension_encoder_3body: 0 5 1 3
number_of_decoding_layers: 2
number_of_decoding_nodes: 25 25
number_of_epochs: 20000

batch_size: 4
activation_function: tanh
alpha_bound: 5.


loss_energy_prefactor: 0.1
loss_force_prefactor: 1.


#expdec initial_learningrate final_learningrate decay_steps
#cosann initial_learningrate first_decaystep t_mul m_mul alpha
lr_dense_net: cosann 0.01 2.5 1.4 0.9 0.00000001
lr_phys_net:  cosann 0.01 2.5 1.4 0.9 0.00000001
optimizer_net: adam
optimizer_phys: adam
loss_method: huber

afs_param_folder: 'path'

Seed: 30
