#yaml input file

#Dataset Path
dataset_folder: files/set.00


#Dataset Path
######How many frames to keep in memory simultaneoulsy
######for descriptor calculation
buffer_stream_dim_ts: 4
buffer_stream_dim_tr: 4
displ_freq: 10
###If you want a random sub sampling indicate (for exmaple) 40 10 for 40 frames to train and
###10 frames to test
subsampling: 'no'

###How you want to name your model?
model_name: 'model_log'
###You want to restart a previous run? indicate the folder of the model from which
###restart. If you want to start a new run but you want to choose your intial afs parama
### indicate only afs and then indicate the folder where the parameter are following the same
### nomenclature of the program.
afs_param_folder: 'afsparam_2'
restart:  'no' #'from_last'

#Descriptor parameter
Rc: 6.5
Rs: 3.25
Radial_Buffer: 80
Rc_Angular: 6.5
Max_Angular_Neigh: 50

#dictionary of types. Key is the type of central particle and word is the sequence of nodes
map_rad_afs: {0: [20,20],1: [20,20]}
map_ang_afs: {0: [13,13,14],1: [13,13,14]}
number_of_decoding_layers: 2
number_of_decoding_nodes: 25 25
number_of_epochs: 20000

batch_size: 4
batch_size_test: 1
activation_function: tanh
alpha_bound: 5.

#expdec initial_learningrate final_learningrate decay_steps
#cosann initial_learningrate first_decaystep t_mul m_mul alpha
lr_dense_net: cosann 0.01 2.5 1.4 0.9 0.00000001
lr_phys_net:  cosann 0.01 2.5 1.4 0.9 0.00000001
optimizer_net: adam
optimizer_phys: adam
loss_method: huber

type_of_training: energy+force

loss_energy_prefactor: 0.1
loss_force_prefactor: 1.0
Seed: 12345
