#yaml input file

#Dataset Path
dataset_folder: /leonardo_work/IscrB_NNPWATER/ALPHAGPU_2/dataset

######How many frames to keep in memory simultaneoulsy
######for descriptor calculation
buffer_stream_dim_ts: 4
buffer_stream_dim_tr: 4
displ_freq: 10
###If you want a random sub sampling indicate (for exmaple) 40 10 for 40 frames to train and 
###10 frames to test
subsampling: 'no'

###How you want to name your model?
model_name: 'model_log'
###You want to restart a previous run? indicate the folder of the model from which 
###restart. If you want to start a new run but you want to choose your intial afs parama
### indicate only afs and then indicate the folder where the parameter are following the same
### nomenclature of the program. 
restart:  'no' 
afs_param_folder: '/leonardo_work/IscrB_NNPWATER/ALPHAGPU_2/afsparam_2'

#Descriptor parameter
Rc: 4.5
Rs: 2.25
Radial_Buffer: 55
Rc_Angular: 4.5
Max_Angular_Neigh: 55

#AFs parameter
Total_number_radial_AFs: 0 10 1 10
Total_number_angular_AFs: 0 60 1 60
map_rad_afs: {0: [10,10],1: [10,10]}
map_ang_afs: {0: [20,20,20],1: [20,20,20]}


#Net parmater
number_of_decoding_layers: 2
number_of_decoding_nodes: 240 240
number_of_epochs: 6000

batch_size: 4
batch_size_test: 1
activation_function: tanh
alpha_bound: 5.


loss_energy_prefactor: 1.
loss_force_prefactor: 1.


type_of_training: energy+force

freq_test: 4

#expdec initial_learningrate final_learningrate decay_steps
#cosann initial_learningrate first_decaystep t_mul m_mul alpha
#lr_dense_net: cosann 0.001 3000 1.4 0.9 0.0000001
#lr_phys_net:  cosann 0.001 3000 1.4 0.9 0.0000001
lr_dense_net: expdec 0.001 0.0000001
lr_phys_net:  expdec 0.001 0.0000001

optimizer_net: adam
optimizer_phys: adam
loss_method: huber

Seed: 0
